services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - "3001:4000"
    volumes:
      - ./infra:/app/infra
      - ./apps/backend/src:/app/apps/backend/src
    environment:
      - NODE_ENV=development
      - PORT=4000
      - LOG_LEVEL=debug
      - JWT_SECRET=test-secret-isb-2024
      - JWT_EXPIRES_IN=24h
      - AUTH_ADMIN_EMAIL=admin@isb-group.fr
      - AUTH_ADMIN_PASSWORD=admin
      - AUTH_ADMIN_NAME=Admin SI
      - CORS_ORIGIN=http://localhost:5173
      - APP_URL=http://localhost:5173
      - CHOKIDAR_USEPOLLING=1

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./apps/frontend/src:/app/apps/frontend/src
    depends_on:
      - backend
    environment:
      - VITE_API_PROXY_TARGET=http://backend:4000
